### ISSUE TITLE
Create database entities(code first)

### ISSUE THREAD

**Issue by vcudalb** [vcudalb/authenticator#14]

**Comment by pmironn472** [comment]
please keep the design architecture of the DB entities as discussed on the hudle

**Comment by vcudalb** [comment]
> please keep the design architecture of the DB entities as discussed on the hudle

Hi @pmironn472,

Thanks for keeping track of the changes and being in touch with proposed architecture.
The general workflow and architecture will be covered by a different task.

P.S. Implementation done under #15 

Best regards,
Vasile
